- name: Install eslint
  become: true
  command: 
  npm:
    name: eslint
    global: yes
  tags:
    - install
    - node
- name: Install Typescript server
  become: true
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - install
    - node
- name: Install Typescript
  become: true
  npm:
    name: typescript
    global: yes
  tags:
    - install
    - node
- name: Install TS-Node
  become: true
  npm:
    name: ts-node
    global: yes
  tags:
    - install
    - node
- name: Install @vue/cli
  become: true
  npm:
    name: "@vue/cli"
    global: true
