- name: Add neovim repository 
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: Install System Packages 
  become: true
  apt:
    pkg:
      - software-properties-common
      - man
      - vim
      - neovim
      - wget
      - curl 
      - nginx
      - mosh 
      - snapd
      - ripgrep
      - tmux
      - make
      - zsh
    state: latest
    update_cache: true
  tags:
    - install
    - neovim
    - core

- name: Install neovim paq
  ansible.builtin.git:
    repo: "https://github.com/savq/paq-nvim.git"
    dest: "~/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    depth: 1 

- name: Change permissions for share directory
  file:
    path: $HOME/.local/share 
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
