- name: Add neovim repository 
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: Install System Packages 
  become: true
  apt:
    pkg:
      - software-properties-common
      - man
      - vim
      - neovim
      - wget
      - curl 
      - nginx
      - snapd
      - ripgrep
      - tmux
      - make
      - zsh
      - zip
    state: latest
    update_cache: true
  tags:
    - install
    - neovim
    - core
