- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && chmod +x stowfiles.sh && ./stowfiles.sh
  tags:
    - install
    - dotfiles
    - stow
