- name: dotnet installation
  tags:
    - dotnet
  block:
    - name: Download dotnet install
      command: wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
    - name: make dotnet install executable 
      command: chmod +x ./dotnet-install.sh
    - name: install dotnet
      command: ./dotnet-install.sh --channel 7.0
    - name: install csharp-ls
      command: dotnet tool install --global csharp-ls

- name: mono installation
  tags:
    - dotnet
  block:
    - name: install apt packages
      become: true
      apt:
        - dirmngr
        - gnupg 
        - apt-transport-https 
        - ca-certificates 
        - software-properties-common
    - name: add mono apt key
      apt_key:
        keyserver: "hkp://keyserver.ubuntu.com:80"
        id: "3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"

    - name: Add mono apt repo
      apt_repository:
        repo: "deb https://download.mono-project.com/repo/ubuntu stable-focal main"
        state: present

    - name: Install mono
      become: true
      apt:
        name: "mono-complete"
        update_cache: yes
        state: latest
