- name: dotnet installation
  tags:
    - dotnet
  block:
    - name: Download dotnet install
      command: wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
    - name: make dotnet install executable 
      command: chmod +x ./dotnet-install.sh
    - name: install dotnet
      command: ./dotnet-install.sh --channel 6.0
      # - name: install csharp-ls
      # command: dotnet tool install --global csharp-ls
