- name: Golang installation
  vars:
    version: 1.23.1
  block:
    - name: Set the correct Go download URL based on OS
      set_fact:
        go_url: >
          https://go.dev/dl/go{{ version }}.{{ 'linux-amd64' if ansible_os_family == 'Debian' else 'darwin-amd64' }}.tar.gz

    - name: Download Go tarball
      command: curl -o go{{ version }}.tar.gz {{ go_url }}

    - name: Remove previous Go installation
      become: true
      command: rm -rf /usr/local/go

    - name: Extract and install Go
      become: true
      command: tar -C /usr/local -xzf go{{ version }}.tar.gz

    - name: Remove downloaded Go tarball
      command: rm -rf go{{ version }}.tar.gz*

    - name: Add Go binary path to profile
      lineinfile:
        path: ~/.profile
        line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
        create: true
        state: present

    - name: Apply profile changes and verify Go installation
      shell: . ~/.profile && go version

  tags:
    - go

- name: Migrate tool installation
  vars:
    version: v4.18.1
  block:
    - name: Set the correct Migrate download URL based on OS
      set_fact:
        migrate_url: >
          https://github.com/golang-migrate/migrate/releases/download/{{ version }}/migrate.{{ 'linux-amd64' if ansible_os_family == 'Debian' else 'darwin-amd64' }}.tar.gz

    - name: Download and extract Migrate binary to /usr/local/bin
      become: true
      unarchive:
        src: "{{ migrate_url }}"
        dest: /usr/local/bin/
        remote_src: yes

  tags:
    - go
