- name: Install System Packages 
  become: true
  apt:
    pkg:
      - automake
      - libtool
      - g++
      - protobuf-compiler
      - libprotobuf-dev
      - libboost-dev
      - libutempter-dev
      - libncurses5-dev 
      - zlib1g-dev 
      - libio-pty-perl 
      - libssl-dev
      - pkg-config
    state: latest
    update_cache: true
  tags:
    - install
    - core
    - mosh


- name: mosh installation
  vars:
    version: 1.4.0
  block:
    - name: Delete previous installation
      command: rm -rf /usr/local/bin/mosh
      become: true
    - name: Download the specified release of mosh and unpack it into /tmp/
      unarchive:
        src: https://github.com/mobile-shell/mosh/releases/download/mosh-{{version}}/mosh-{{version}}.tar.gz 
        dest: /tmp/
        remote_src: yes
    - name: Install mosh
      become: true
      shell: |
        cd /tmp/mosh-{{version}}
        ./autogen.sh
        ./configure
        make
        make install
    - name: Delete downloaded tar file
      become: true
      shell: rm -rf /tmp/mosh-{{version}}  
  tags:
    - install
    - core
    - mosh
