- name: Install neovim paq
  ansible.builtin.git:
    repo: "https://github.com/savq/paq-nvim.git"
    dest: "~/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    depth: 1
  tags:
    - neovim

- name: Change permissions for share directory
  file:
    path: $HOME/.local/share 
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
  tags:
    - neovim

- name: Run Paq Install
  shell: cd $HOME/.config/nvim && nvim --headless +so +PaqInstall +q 
  tags:
  - neovim

- name: Wait until package.json is present before continuing
  ansible.builtin.wait_for:
    path: $HOME/.local/share/nvim/site/pack/paqs/start/coc.nvim/package.json 

- name: Install COC
  shell: cd $HOME/.local/share/nvim/site/pack/paqs/start/coc.nvim/ && npm install
  tags:
  - neovim
    
- name: Install COC Extensions
  shell: cd $HOME/.config/coc/extensions && npm install
  tags:
  - neovim
