- name: Install neovim Paq package manager
  ansible.builtin.git:
    repo: "https://github.com/savq/paq-nvim.git"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    depth: 1
  tags:
    - neovim

- name: Change permissions for .local/share directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    recurse: yes 
  tags:
    - neovim

- name: Run PaqInstall
  shell: cd {{ ansible_env.HOME }}/.config/nvim && nvim --headless +so +PaqInstall +q
  tags:
    - neovim
