- name: Install neovim paq
  ansible.builtin.git:
    repo: "https://github.com/savq/paq-nvim.git"
    dest: "~/.local/share/nvim/site/pack/paqs/start/paq-nvim"
    depth: 1
  tags:
    - neovim

- name: Change permissions for share directory
  file:
    path: $HOME/.local/share 
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
  tags:
    - neovim

- name: Run Paq Install
  shell: cd $HOME/.config/nvim && nvim --headless +so +PaqInstall +q 
  tags:
  - neovim


- name: Install COC
  shell: cd $HOME/.local/share/nvim/site/pack/paqs/start/coc.nvim/ && yarn install
  tags:
  - neovim
    
- name: Install COC Extensions
  shell: cd $HOME/.config/coc/extensions && yarn install
  tags:
  - neovim
