- name: Install npm (Debian/Ubuntu)
  become: true
  apt:
    name: npm
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - node

- name: Install npm (macOS)
  become: true
  homebrew:
    name: npm
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - node

- name: Install Node.js version manager 'n' globally
  become: true
  npm:
    name: n
    global: yes
  tags:
    - node

- name: Upgrade to the latest stable version of Node.js
  become: true
  command: n stable
  tags:
    - node
