- name: Install Python packages
  become: true
  apt:
    pkg:
      - python3-pip
      - python3.8-venv
    state: latest
    update_cache: true
  tags:
    - python

- name: Install Poetry
  command: curl -sSL https://install.python-poetry.org | python3 - 
  tags:
    - python
