- name: Install Python packages (Debian/Ubuntu)
  become: true
  apt:
    pkg:
      - python3-pip
      - python3-venv
    state: latest
    update_cache: true
  when: ansible_os_family == "Debian"
  tags:
    - python

- name: Install Python packages (macOS)
  become: true
  homebrew:
    name:
      - python3
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - python

- name: Install Poetry
  shell: |
    curl -sSL https://install.python-poetry.org | python3 -
  tags:
    - python
