- name: Clone LeetCode repo                                         
  git:                                                                          
    repo: git@github.com:aleksvagapitov/LeetCode.git 
    dest: "~/LeetCode"                                                         
    accept_hostkey: yes                                                         
    key_file: "~/.ssh/github"
  tags:
    - repositories

- name: Clone DSA repo                                         
  git:                                                                          
    repo: git@github.com:aleksvagapitov/dsa.git 
    dest: "~/DSA"                                                         
    accept_hostkey: yes                                                         
    key_file: "~/.ssh/github"
  tags:
    - repositories

- name: Clone kata-machine repo                                         
  git:                                                                          
    repo: git@github.com:aleksvagapitov/kata-machine.git 
    dest: "~/kata-machine"                                                         
    accept_hostkey: yes                                                         
    key_file: "~/.ssh/github"
  tags:
    - repositories

- name: Clone Udemy repo                                         
  git:                                                                          
    repo: git@github.com:aleksvagapitov/Udemy.git 
    dest: "~/Udemy"                                                         
    accept_hostkey: yes                                                         
    key_file: "~/.ssh/github"
  tags:
    - repositories
