- name: Clone aleksvagapitov repo                                         
  git:                                                                          
    repo: git@github.com:aleksvagapitov/aleksvagapitov.github.io.git 
    dest: "~/aleksvagapitov.github.io"                                                         
    accept_hostkey: yes                                                         
    key_file: "~/.ssh/github"
  tags:
    - repositories

- name: Clone Courses repo                                         
  git:                                                                          
    repo: git@github.com:aleksvagapitov/Courses.git 
    dest: "~/Courses"                                                         
    accept_hostkey: yes                                                         
    key_file: "~/.ssh/github"
  tags:
    - repositories

- name: Clone Practice repo                                         
  git:                                                                          
    repo: git@github.com:aleksvagapitov/Practice.git 
    dest: "~/Practice"                                                         
    accept_hostkey: yes                                                         
    key_file: "~/.ssh/github"
  tags:
    - repositories
