- name: Install zsh
  apt: name=zsh
  tags:
    - zsh

- name: Change shell
  become_user: true 
  shell: chsh $USER -s $(which zsh)
  tags:
    - zsh

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Install zsh-completions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions.git'
    dest: "~/.oh-my-zsh/custom/plugins/zsh-completions"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
