- hosts: localhost
  pre_tasks:
  - name: Update Cache
    become: true 
    apt:
      update-cache: true
    tags:
      - core
      - mosh
      - dotfiles
      - go
      - node
      - python
      - zsh
      - dotnet
      - github
  tasks:
  - include: tasks/core.yml
  - include: tasks/mosh.yml
  - include: tasks/node-setup.yml
  - include: tasks/zsh.yml
  - include: tasks/dotfiles.yml
  - include: tasks/neovim.yml
  - include: tasks/npm-packages.yml
  - include: tasks/dotnet.yml
  - include: tasks/golang.yml
  - include: tasks/python.yml
  - include: tasks/repositories.yml
