- hosts: localhost
  pre_tasks:
  - name: Update Cache
    become: true 
    apt:
      update-cache: true
    tags:
      - core
      - mosh
      - dotfiles
      - go
      - bun
      - node
      - python
      - zsh
      - dotnet
      - github
  - name: Wait for sudo
    become: yes
    shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
  tasks:
  - import_tasks: tasks/core.yml
  - import_tasks: tasks/mosh.yml
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/bun.yml
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/neovim.yml
  - import_tasks: tasks/dotnet.yml
  - import_tasks: tasks/golang.yml
  - import_tasks: tasks/python.yml
  - import_tasks: tasks/repositories.yml
